name: 部署静态网站

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 部署静态网站
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/qingyun/team1
            git pull origin main
            fuser -k 8001/tcp || true
            nohup python3 -m http.server 8001 > server.log 2>&1 &
